image: androidsdk/android-30

pipelines:
  default:
      - step:
          name: Android Debug Application
          script:
            - ./gradlew assembleDebug
            - pipe: atlassian/git-secrets-scan:0.4.3
